wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 10
hidden_layer_size:
  value: 64
hidden_layers:
  value: 3
learning_rate:
  value: 0.0001
optimiser:
  value: rmsprop
weight_decay:
  value: 0.5
weight_init:
  value: xavier
