wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
hidden_layer_size:
  value: 128
hidden_layers:
  value: 3
learning_rate:
  value: 0.001
optimiser:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: xavier
