wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 10
hidden_layer_size:
  value: 128
hidden_layers:
  value: 5
learning_rate:
  value: 0.0001
optimiser:
  value: momentum
weight_decay:
  value: 0
weight_init:
  value: xavier
