wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
hidden_size:
  value: 64
learning_rate:
  value: 0.001
num_layers:
  value: 4
optimizer:
  value: sgd
weight_decay:
  value: 0.5
weight_init:
  value: random
