wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 10
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
num_layers:
  value: 4
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
