wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 5
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
num_layers:
  value: 5
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
