wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
num_layers:
  value: 4
optimizer:
  value: momentum
weight_decay:
  value: 0
weight_init:
  value: random
