wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 64
hidden_layers:
  value: 5
learning_rate:
  value: 0.001
optimiser:
  value: adam
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
