wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 128
hidden_layers:
  value: 3
learning_rate:
  value: 0.0001
optimiser:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
