wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 10
hidden_layer_size:
  value: 32
hidden_layers:
  value: 5
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
optimiser:
  value: nadam
weight_decay:
  value: 0.5
weight_init:
  value: xavier
