wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 10
hidden_layer_size:
  value: 32
hidden_layers:
  value: 4
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
optimiser:
  value: rmsprop
weight_decay:
  value: 0.5
weight_init:
  value: random
