wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 10
hidden_layer_size:
  value: 128
hidden_layers:
  value: 3
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
optimiser:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: random
