wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 128
hidden_layers:
  value: 5
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
optimiser:
  value: nesterov
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
