wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 10
hidden_layer_size:
  value: 32
hidden_layers:
  value: 5
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
optimiser:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: random
