wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 128
hidden_layers:
  value: 4
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
optimiser:
  value: nesterov
weight_decay:
  value: 0.5
weight_init:
  value: xavier
