wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
hidden_layer_size:
  value: 32
hidden_layers:
  value: 3
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
optimiser:
  value: sgd
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
