wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.5
    cli_version: 0.16.1
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1741550933.212496
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 105
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 105
      3:
      - 2
      - 13
      - 19
      - 23
      4: 3.9.5
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 5
num_layers:
  desc: null
  value: 3
hidden_size:
  desc: null
  value: 128
activation:
  desc: null
  value: tanh
weight_init:
  desc: null
  value: xavier
loss:
  desc: null
  value: cross_entropy
optimizer:
  desc: null
  value: nadam
momentum:
  desc: null
  value: 0.9
beta:
  desc: null
  value: 0.9
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.999
epsilon:
  desc: null
  value: 1.0e-08
weight_decay:
  desc: null
  value: 0.0005
