wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 32
hidden_layers:
  value: 3
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
optimiser:
  value: momentum
weight_decay:
  value: 0.5
weight_init:
  value: xavier
