wandb_version: 1

activation:
  desc: null
  value: sigmoid
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 5
hidden_layer_size:
  desc: null
  value: 128
hidden_layers:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.0001
optimiser:
  desc: null
  value: adam
weight_decay:
  desc: null
  value: 0.0005
weight_init:
  desc: null
  value: xavier
_wandb:
  desc: null
  value:
    python_version: 3.9.5
    cli_version: 0.16.1
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1741509480.333504
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 105
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 105
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.9.5
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
