wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.5
    cli_version: 0.16.1
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1741384328.183337
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 105
      3:
      - 23
      4: 3.9.5
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
